### ISSUE TITLE
i can't get this to work

### ISSUE THREAD

**Issue by machty** [pangratz/ember.js-dashboard#24]

**Comment by pangratz** [comment]
![:glasses:](https://media.giphy.com/media/FPjbHO0jJxGsE/giphy.gif)

---

Uff, it's been a while since I looked at this repo 👴  . Good old pre ember-cli and ember 0.9.6 😍 

I currently don't have the bandwidth to look into this, but a running version is deployed at http://code418.com/ember.js-dashboard/ ...

**Comment by machty** [comment]
lolz, I was just trollin.

:trollface:

**Comment by pangratz** [comment]
Damn, and I removed the `Not sure if you are trolling` intro from my comment 😔  Should have known better. Well played sir, well played 🍷  .
